### ISSUE TITLE
LOAD THE DATABASE DUMP

### ISSUE THREAD

**Issue by John-26** [xingdl2007/cmu15-445#1]
你好,请问怎么把md_courts.dump加载如sqlite 呢?
搜了好久一直不会.

**Comment by xingdl2007** [comment]
参考这里 [10. Converting An Entire Database To An ASCII Text File](https://www.sqlite.org/cli.html)

**Comment by John-26** [comment]
不好意思能详细指导下么, 那个好像是linux命令, 我是windows平台的.
